"use client";

import { FormEvent, useEffect, useState } from "react";
import { BriefcaseBusiness, MapPin, Plus, Trash2, X } from "lucide-react";
import { deleteRole, getRoles, saveRole } from "../lib/api";
import type { Role, RoleInput } from "../lib/types";

const emptyRole: RoleInput = { title: "", department: "", location: "", work_mode: "Hybrid", description: "", status: "open" };

export function OpenRoles({ apiKey, onSearch }: { apiKey: string; onSearch: (query: string) => void }) {
  const [roles, setRoles] = useState<Role[]>([]); const [editing, setEditing] = useState<Role | null>(null); const [form, setForm] = useState<RoleInput>(emptyRole); const [modal, setModal] = useState(false); const [error, setError] = useState("");
  const load = async () => { try { setRoles(await getRoles(apiKey)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load roles."); } };
  useEffect(() => { getRoles(apiKey).then(setRoles).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Could not load roles.")); }, [apiKey]);
  const openForm = (role?: Role) => { setEditing(role ?? null); setForm(role ? { title: role.title, department: role.department, location: role.location, work_mode: role.work_mode, description: role.description, status: role.status } : emptyRole); setModal(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); try { await saveRole(form, apiKey, editing?.id); setModal(false); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save role."); } };
  const remove = async (id: string) => { if (!window.confirm("Delete this role?")) return; await deleteRole(id, apiKey); await load(); };
  return <section className="content-view"><div className="view-heading"><div><span className="eyebrow">Hiring plan</span><h1>Open roles</h1><p>Create roles and turn their job descriptions into candidate searches.</p></div><button onClick={() => openForm()} className="button-primary"><Plus size={15} /> New role</button></div>{error && <p className="error-banner">{error}</p>}
    {roles.length === 0 ? <div className="empty-state"><BriefcaseBusiness /><strong>No roles yet</strong><span>Create your first opening to start matching candidates.</span></div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{roles.map((role) => <article key={role.id} className="role-card"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><BriefcaseBusiness size={18} /></span><span className={`status status-${role.status}`}>{role.status}</span></div><h2>{role.title}</h2><p className="line-clamp-3">{role.description}</p><div className="mt-5 flex flex-wrap gap-2 text-xs text-slate-500"><span>{role.department || "General"}</span><span className="flex items-center gap-1"><MapPin size={12} />{role.location || "Flexible"}</span><span>{role.work_mode}</span></div><div className="mt-5 flex gap-2 border-t border-slate-100 pt-4"><button onClick={() => onSearch(role.description)} className="button-primary flex-1">Find candidates</button><button onClick={() => openForm(role)} className="button-secondary">Edit</button><button onClick={() => void remove(role.id)} className="icon-button danger"><Trash2 size={15} /></button></div></article>)}</div>}
    {modal && <div className="modal-backdrop"><form onSubmit={submit} className="modal-card"><div className="flex items-start justify-between"><div><h2>{editing ? "Edit role" : "Create a role"}</h2><p>Add the role details and complete job description.</p></div><button type="button" onClick={() => setModal(false)} className="icon-button"><X size={17} /></button></div><div className="form-grid"><label>Role title<input required minLength={2} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Department<input value={form.department} onChange={(e) => setForm({ ...form, department: e.target.value })} /></label><label>Location<input value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /></label><label>Work mode<select value={form.work_mode} onChange={(e) => setForm({ ...form, work_mode: e.target.value })}><option>Remote</option><option>Hybrid</option><option>On-site</option></select></label><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as RoleInput["status"] })}><option value="open">Open</option><option value="paused">Paused</option><option value="closed">Closed</option></select></label><label className="full">Job description<textarea required minLength={10} rows={8} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setModal(false)} className="button-secondary">Cancel</button><button className="button-primary">{editing ? "Save changes" : "Create role"}</button></div></form></div>}
  </section>;
}
