"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, Check, ChevronDown, CircleUserRound, FileUp, KeyRound, LoaderCircle, MessageSquareText, Search, Send, SlidersHorizontal, Users, X } from "lucide-react";
import { explainCandidate, getRecentSearches, searchCandidates } from "../lib/api";
import type { Candidate, Explanation, RecentSearch } from "../lib/types";
import { BrandMark } from "./BrandMark";
import { CandidateCard } from "./CandidateCard";
import { OpenRoles } from "./OpenRoles";
import { RecentSearches } from "./RecentSearches";
import { TalentPool } from "./TalentPool";

const prompts = ["Senior Python engineer with FastAPI and AWS experience", "QA automation lead with Selenium and CI/CD", "React Native developer with shipped consumer apps"];

export function RecruiterWorkspace({ onApply }: { onApply: () => void }) {
  const [view, setView] = useState<"search" | "talent" | "roles" | "history">("search");
  const [query, setQuery] = useState(""); const [lastQuery, setLastQuery] = useState(""); const [limit, setLimit] = useState(5);
  const [experience, setExperience] = useState(""); const [workMode, setWorkMode] = useState("");
  const [candidates, setCandidates] = useState<Candidate[]>([]); const [explanations, setExplanations] = useState<Record<string, Explanation>>({});
  const [loading, setLoading] = useState(false); const [explaining, setExplaining] = useState<string | null>(null); const [error, setError] = useState("");
  const [apiKey, setApiKey] = useState(() => typeof window === "undefined" ? "" : sessionStorage.getItem("candidate-api-key") ?? ""); const [showKey, setShowKey] = useState(false);
  const [recentSearches, setRecentSearches] = useState<RecentSearch[]>([]);
  const average = useMemo(() => candidates.length ? Math.round(candidates.reduce((sum, item) => sum + item.score, 0) / candidates.length * 100) : 0, [candidates]);
  const loadRecent = async () => { try { setRecentSearches(await getRecentSearches(apiKey)); } catch { setRecentSearches([]); } };
  useEffect(() => { getRecentSearches(apiKey).then(setRecentSearches).catch(() => setRecentSearches([])); }, [apiKey]);
  const submit = async (event?: FormEvent, value = query) => { event?.preventDefault(); if (value.trim().length < 2) return; const filterText = [value.trim(), experience && `${experience} experience`, workMode && `${workMode} work preference`].filter(Boolean).join(". "); setView("search"); setLoading(true); setError(""); setLastQuery(filterText); setExplanations({}); try { setCandidates((await searchCandidates(filterText, limit, apiKey)).results); await loadRecent(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Search failed."); setCandidates([]); } finally { setLoading(false); } };
  const explain = async (candidate: Candidate) => { setExplaining(candidate.resume_id); setError(""); try { const result = await explainCandidate(candidate.resume_id, lastQuery, apiKey); setExplanations((current) => ({ ...current, [candidate.resume_id]: result })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not explain this match."); } finally { setExplaining(null); } };
  const saveKey = (value: string) => { setApiKey(value); sessionStorage.setItem("candidate-api-key", value); };

  return <div className="flex min-h-screen bg-[#F5F6F2] text-slate-950">
    <aside className="hidden w-[248px] shrink-0 flex-col border-r border-slate-200/80 bg-white p-5 lg:flex"><BrandMark /><nav className="mt-9 space-y-1"><button onClick={() => setView("search")} className={`nav-item ${view === "search" ? "nav-item-active" : ""}`}><MessageSquareText size={17} /> Candidate search</button><button onClick={onApply} className="nav-item"><FileUp size={17} /> Application portal</button><button onClick={() => setView("talent")} className={`nav-item ${view === "talent" ? "nav-item-active" : ""}`}><Users size={17} /> Talent pool</button><button onClick={() => setView("roles")} className={`nav-item ${view === "roles" ? "nav-item-active" : ""}`}><BriefcaseBusiness size={17} /> Open roles</button></nav><div className="mt-8 border-t border-slate-100 pt-6"><button onClick={() => setView("history")} className="flex w-full items-center justify-between px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400 hover:text-slate-700"><span>Recent searches</span><span>{recentSearches.length}</span></button><div className="mt-3 space-y-1">{recentSearches.slice(0, 3).map((item) => <button key={item.id} onClick={() => { setQuery(item.query); void submit(undefined, item.query); }} className="w-full truncate rounded-lg px-3 py-2 text-left text-xs text-slate-500 hover:bg-slate-50 hover:text-slate-900">{item.query}</button>)}</div></div><div className="mt-auto rounded-2xl bg-[#F1F4F1] p-3.5"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-[#173F35] text-white"><CircleUserRound size={18} /></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">Recruiting team</p><p className="truncate text-[11px] text-slate-400">Hiring workspace</p></div><ChevronDown size={14} className="text-slate-400" /></div></div></aside>
    <main className="min-w-0 flex-1"><header className="flex h-[72px] items-center justify-between border-b border-slate-200/80 bg-white/80 px-5 backdrop-blur sm:px-8"><div className="lg:hidden"><BrandMark compact /></div><div className="hidden lg:block"><p className="text-sm font-semibold">{view === "search" ? "Candidate search" : view === "talent" ? "Talent pool" : view === "roles" ? "Open roles" : "Recent searches"}</p><p className="text-xs text-slate-400">Recruiting workspace</p></div><div className="flex items-center gap-2"><button onClick={() => setShowKey(true)} className={`button-quiet ${apiKey ? "text-emerald-700" : ""}`}><KeyRound size={15} /> <span className="hidden sm:inline">API access</span>{apiKey && <span className="size-1.5 rounded-full bg-emerald-500" />}</button><button onClick={onApply} className="button-secondary"><FileUp size={14} /> <span className="hidden sm:inline">Application portal</span></button></div></header>
      {view === "search" ? <div className="mx-auto max-w-6xl px-5 py-9 sm:px-8 lg:py-12"><section className="max-w-3xl"><span className="eyebrow"><span className="size-1.5 rounded-full bg-emerald-500" /> AI talent search</span><h1 className="mt-4 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Who are you looking for?</h1><p className="mt-3 text-sm leading-6 text-slate-500">Describe the ideal candidate or paste a job description. Shortlist will find the strongest profiles and show you why.</p></section>
        <form onSubmit={submit} className="mt-8 rounded-2xl border border-slate-200 bg-white p-2 shadow-[0_12px_35px_rgba(28,44,38,0.06)] focus-within:border-emerald-700/40 focus-within:ring-4 focus-within:ring-emerald-700/5"><textarea value={query} onChange={(e) => setQuery(e.target.value)} rows={4} placeholder="Try: Senior backend engineer with 5+ years of Python, FastAPI, PostgreSQL and cloud infrastructure…" className="w-full resize-none bg-transparent px-4 py-3 text-sm leading-6 outline-none placeholder:text-slate-400" /><div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 px-2 pt-2"><div className="flex flex-wrap items-center gap-1"><span className="flex items-center gap-1.5 rounded-lg px-2 py-2 text-xs text-slate-500"><SlidersHorizontal size={14} /> Filters</span><select aria-label="Experience level" value={experience} onChange={(e) => setExperience(e.target.value)} className="filter-select"><option value="">Any experience</option><option>Entry level</option><option>Mid level</option><option>Senior</option><option>Lead</option></select><select aria-label="Work preference" value={workMode} onChange={(e) => setWorkMode(e.target.value)} className="filter-select"><option value="">Any location</option><option>Remote</option><option>Hybrid</option><option>On-site</option></select><select aria-label="Number of candidates" value={limit} onChange={(e) => setLimit(Number(e.target.value))} className="filter-select">{[3, 5, 10, 15].map((number) => <option key={number} value={number}>{number} results</option>)}</select></div><button disabled={loading || query.trim().length < 2} className="button-primary !px-4 !py-2.5 disabled:opacity-40">{loading ? <LoaderCircle size={15} className="animate-spin" /> : <Send size={14} />} Find candidates</button></div></form>
        {!lastQuery && <div className="mt-6"><p className="text-xs font-medium text-slate-400">Or start with an example</p><div className="mt-3 flex flex-wrap gap-2">{prompts.map((item) => <button key={item} onClick={() => { setQuery(item); void submit(undefined, item); }} className="rounded-full border border-slate-200 bg-white px-3.5 py-2 text-xs text-slate-500 transition hover:border-slate-300 hover:text-slate-900">{item}</button>)}</div></div>}
        {error && <div role="alert" className="mt-5 flex items-center justify-between rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"><span>{error}</span><button onClick={() => setError("")}><X size={15} /></button></div>}
        {lastQuery && !loading && <section className="mt-10"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-400">Search results</p><h2 className="mt-1 text-xl font-semibold tracking-tight">{candidates.length} candidates shortlisted</h2></div>{candidates.length > 0 && <div className="flex items-center gap-4 text-xs text-slate-400"><span><strong className="text-slate-700">{average}%</strong> average relevance</span><span className="flex items-center gap-1.5"><Check size={13} className="text-emerald-600" /> Ranked by evidence</span></div>}</div>{candidates.length ? <div className="grid gap-3 xl:grid-cols-2">{candidates.map((candidate, index) => <CandidateCard key={candidate.resume_id} candidate={candidate} index={index} explanation={explanations[candidate.resume_id]} explaining={explaining === candidate.resume_id} onExplain={() => void explain(candidate)} apiKey={apiKey} />)}</div> : <div className="rounded-2xl border border-dashed border-slate-300 bg-white/50 py-16 text-center"><Search className="mx-auto text-slate-300" size={26} /><p className="mt-4 text-sm font-semibold">No matching candidates found</p><p className="mt-1 text-xs text-slate-400">Try broadening the role, skills, or experience level.</p></div>}</section>}
      </div> : view === "talent" ? <TalentPool apiKey={apiKey} /> : view === "roles" ? <OpenRoles apiKey={apiKey} onSearch={(value) => { setQuery(value); void submit(undefined, value); }} /> : <RecentSearches items={recentSearches} apiKey={apiKey} onRefresh={loadRecent} onRun={(value) => { setQuery(value); void submit(undefined, value); }} />}</main>
    <nav className="mobile-nav"><button onClick={() => setView("search")} className={view === "search" ? "active" : ""}><MessageSquareText size={17} /><span>Search</span></button><button onClick={() => setView("talent")} className={view === "talent" ? "active" : ""}><Users size={17} /><span>Talent</span></button><button onClick={() => setView("roles")} className={view === "roles" ? "active" : ""}><BriefcaseBusiness size={17} /><span>Roles</span></button><button onClick={() => setView("history")} className={view === "history" ? "active" : ""}><Search size={17} /><span>History</span></button></nav>
    {showKey && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/30 p-5 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold">Connect to the API</h2><p className="mt-1 text-sm text-slate-500">Enter the key configured on your backend.</p></div><button onClick={() => setShowKey(false)} className="rounded-lg p-2 hover:bg-slate-100"><X size={16} /></button></div><label className="mt-6 block text-xs font-semibold text-slate-700">API key<input type="password" value={apiKey} onChange={(e) => saveKey(e.target.value)} placeholder="Your X-API-Key" className="mt-2 w-full rounded-xl border border-slate-200 px-3.5 py-3 text-sm outline-none focus:border-emerald-700" /></label><button onClick={() => setShowKey(false)} className="button-primary mt-5 w-full">Save access key</button><p className="mt-3 text-center text-[11px] text-slate-400">Stored only for this browser session.</p></div></div>}
  </div>;
}
